// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package HelloGrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// HelloGrpcClient is the client API for HelloGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloGrpcClient interface {
	// Sends a greeting
	GreetServer(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetMessage, error)
	// チャットルーム追加
	AddRoom(ctx context.Context, in *RoomRequest, opts ...grpc.CallOption) (*RoomInfo, error)
	// チャットルーム情報取得
	GetRoomInfo(ctx context.Context, in *RoomRequest, opts ...grpc.CallOption) (*RoomInfo, error)
	// チャットルーム一覧取得
	GetRooms(ctx context.Context, in *Null, opts ...grpc.CallOption) (*RoomList, error)
	// Client-side streamingを用いてメッセージを交換する
	SendMessage(ctx context.Context, opts ...grpc.CallOption) (HelloGrpc_SendMessageClient, error)
	// Server-side streamingを用いてメッセージを交換する
	GetMessages(ctx context.Context, in *MessagesRequest, opts ...grpc.CallOption) (HelloGrpc_GetMessagesClient, error)
}

type helloGrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloGrpcClient(cc grpc.ClientConnInterface) HelloGrpcClient {
	return &helloGrpcClient{cc}
}

func (c *helloGrpcClient) GreetServer(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetMessage, error) {
	out := new(GreetMessage)
	err := c.cc.Invoke(ctx, "/HelloGrpc.HelloGrpc/GreetServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloGrpcClient) AddRoom(ctx context.Context, in *RoomRequest, opts ...grpc.CallOption) (*RoomInfo, error) {
	out := new(RoomInfo)
	err := c.cc.Invoke(ctx, "/HelloGrpc.HelloGrpc/AddRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloGrpcClient) GetRoomInfo(ctx context.Context, in *RoomRequest, opts ...grpc.CallOption) (*RoomInfo, error) {
	out := new(RoomInfo)
	err := c.cc.Invoke(ctx, "/HelloGrpc.HelloGrpc/GetRoomInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloGrpcClient) GetRooms(ctx context.Context, in *Null, opts ...grpc.CallOption) (*RoomList, error) {
	out := new(RoomList)
	err := c.cc.Invoke(ctx, "/HelloGrpc.HelloGrpc/GetRooms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloGrpcClient) SendMessage(ctx context.Context, opts ...grpc.CallOption) (HelloGrpc_SendMessageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HelloGrpc_serviceDesc.Streams[0], "/HelloGrpc.HelloGrpc/SendMessage", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloGrpcSendMessageClient{stream}
	return x, nil
}

type HelloGrpc_SendMessageClient interface {
	Send(*SendRequest) error
	CloseAndRecv() (*SendResult, error)
	grpc.ClientStream
}

type helloGrpcSendMessageClient struct {
	grpc.ClientStream
}

func (x *helloGrpcSendMessageClient) Send(m *SendRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *helloGrpcSendMessageClient) CloseAndRecv() (*SendResult, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SendResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *helloGrpcClient) GetMessages(ctx context.Context, in *MessagesRequest, opts ...grpc.CallOption) (HelloGrpc_GetMessagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HelloGrpc_serviceDesc.Streams[1], "/HelloGrpc.HelloGrpc/GetMessages", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloGrpcGetMessagesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HelloGrpc_GetMessagesClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type helloGrpcGetMessagesClient struct {
	grpc.ClientStream
}

func (x *helloGrpcGetMessagesClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HelloGrpcServer is the server API for HelloGrpc service.
// All implementations should embed UnimplementedHelloGrpcServer
// for forward compatibility
type HelloGrpcServer interface {
	// Sends a greeting
	GreetServer(context.Context, *GreetRequest) (*GreetMessage, error)
	// チャットルーム追加
	AddRoom(context.Context, *RoomRequest) (*RoomInfo, error)
	// チャットルーム情報取得
	GetRoomInfo(context.Context, *RoomRequest) (*RoomInfo, error)
	// チャットルーム一覧取得
	GetRooms(context.Context, *Null) (*RoomList, error)
	// Client-side streamingを用いてメッセージを交換する
	SendMessage(HelloGrpc_SendMessageServer) error
	// Server-side streamingを用いてメッセージを交換する
	GetMessages(*MessagesRequest, HelloGrpc_GetMessagesServer) error
}

// UnimplementedHelloGrpcServer should be embedded to have forward compatible implementations.
type UnimplementedHelloGrpcServer struct {
}

func (UnimplementedHelloGrpcServer) GreetServer(context.Context, *GreetRequest) (*GreetMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GreetServer not implemented")
}
func (UnimplementedHelloGrpcServer) AddRoom(context.Context, *RoomRequest) (*RoomInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRoom not implemented")
}
func (UnimplementedHelloGrpcServer) GetRoomInfo(context.Context, *RoomRequest) (*RoomInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoomInfo not implemented")
}
func (UnimplementedHelloGrpcServer) GetRooms(context.Context, *Null) (*RoomList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRooms not implemented")
}
func (UnimplementedHelloGrpcServer) SendMessage(HelloGrpc_SendMessageServer) error {
	return status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedHelloGrpcServer) GetMessages(*MessagesRequest, HelloGrpc_GetMessagesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetMessages not implemented")
}

// UnsafeHelloGrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelloGrpcServer will
// result in compilation errors.
type UnsafeHelloGrpcServer interface {
	mustEmbedUnimplementedHelloGrpcServer()
}

func RegisterHelloGrpcServer(s grpc.ServiceRegistrar, srv HelloGrpcServer) {
	s.RegisterService(&_HelloGrpc_serviceDesc, srv)
}

func _HelloGrpc_GreetServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloGrpcServer).GreetServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HelloGrpc.HelloGrpc/GreetServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloGrpcServer).GreetServer(ctx, req.(*GreetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelloGrpc_AddRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloGrpcServer).AddRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HelloGrpc.HelloGrpc/AddRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloGrpcServer).AddRoom(ctx, req.(*RoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelloGrpc_GetRoomInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloGrpcServer).GetRoomInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HelloGrpc.HelloGrpc/GetRoomInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloGrpcServer).GetRoomInfo(ctx, req.(*RoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelloGrpc_GetRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Null)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloGrpcServer).GetRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HelloGrpc.HelloGrpc/GetRooms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloGrpcServer).GetRooms(ctx, req.(*Null))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelloGrpc_SendMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HelloGrpcServer).SendMessage(&helloGrpcSendMessageServer{stream})
}

type HelloGrpc_SendMessageServer interface {
	SendAndClose(*SendResult) error
	Recv() (*SendRequest, error)
	grpc.ServerStream
}

type helloGrpcSendMessageServer struct {
	grpc.ServerStream
}

func (x *helloGrpcSendMessageServer) SendAndClose(m *SendResult) error {
	return x.ServerStream.SendMsg(m)
}

func (x *helloGrpcSendMessageServer) Recv() (*SendRequest, error) {
	m := new(SendRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _HelloGrpc_GetMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MessagesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HelloGrpcServer).GetMessages(m, &helloGrpcGetMessagesServer{stream})
}

type HelloGrpc_GetMessagesServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type helloGrpcGetMessagesServer struct {
	grpc.ServerStream
}

func (x *helloGrpcGetMessagesServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

var _HelloGrpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "HelloGrpc.HelloGrpc",
	HandlerType: (*HelloGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GreetServer",
			Handler:    _HelloGrpc_GreetServer_Handler,
		},
		{
			MethodName: "AddRoom",
			Handler:    _HelloGrpc_AddRoom_Handler,
		},
		{
			MethodName: "GetRoomInfo",
			Handler:    _HelloGrpc_GetRoomInfo_Handler,
		},
		{
			MethodName: "GetRooms",
			Handler:    _HelloGrpc_GetRooms_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendMessage",
			Handler:       _HelloGrpc_SendMessage_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetMessages",
			Handler:       _HelloGrpc_GetMessages_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chatgrpc/chatgrpc.proto",
}
